let words = [
	{ eng: "as", rus: "как" },
	{ eng: "I", rus: "я" },
	{ eng: "his", rus: "его" },
	{ eng: "that", rus: "что / тот" },
	{ eng: "he", rus: "он" },
	{ eng: "was", rus: "был" },
	{ eng: "for", rus: "для" },
	{ eng: "on", rus: "на" },
	{ eng: "are", rus: "являются" },
	{ eng: "with", rus: "с" },
	{ eng: "they", rus: "они" },
	{ eng: "be", rus: "быть" },
	{ eng: "at", rus: "на" },
	{ eng: "one", rus: "один" },
	{ eng: "have", rus: "иметь" },
	{ eng: "this", rus: "это" },
	{ eng: "from", rus: "из" },
	{ eng: "by", rus: "от" },
	{ eng: "hot", rus: "горячий / жарко" },
	{ eng: "word", rus: "слово" },
	{ eng: "but", rus: "но" },
	{ eng: "what", rus: "что" },
	{ eng: "some", rus: "некоторый" },
	{ eng: "is", rus: "является" },
	{ eng: "it", rus: "это" },
	{ eng: "you", rus: "ты" },
	{ eng: "or", rus: "или" },
	{ eng: "had", rus: "имел" },
	{ eng: "the", rus: "" },
	{ eng: "of", rus: "из / о" },
	{ eng: "to", rus: "в / к" },
	{ eng: "and", rus: "и" },
	{ eng: "a", rus: "" },
	{ eng: "in", rus: "в" },
	{ eng: "we", rus: "мы" },
	{ eng: "can", rus: "может" },
	{ eng: "out", rus: "из / вне" },
	{ eng: "other", rus: "другой" },
	{ eng: "were", rus: "были" },
	{ eng: "which", rus: "который" },
	{ eng: "do", rus: "делать" },
	{ eng: "their", rus: "их" },
	{ eng: "time", rus: "время" },
	{ eng: "if", rus: "если" },
	{ eng: "will ", rus: " будет" },
	{ eng: "how", rus: "как" },
	{ eng: "said", rus: "говорить" },
	{ eng: "an", rus: "" },
	{ eng: "each", rus: "каждый" },
	{ eng: "tell", rus: "говорить" },
	{ eng: "does", rus: "делает" },
	{ eng: "set", rus: "задавать / комплект" },
	{ eng: "three", rus: "три" },
	{ eng: "want", rus: "хотеть" },
	{ eng: "air", rus: "воздух" },
	{ eng: "well  ", rus: " хорошо" },
	{ eng: "also", rus: "также" },
	{ eng: "play", rus: "играть" },
	{ eng: "small", rus: "маленький" },
	{ eng: "end", rus: "конец" },
	{ eng: "put", rus: "ставить" },
	{ eng: "home", rus: "дом" },
	{ eng: "read", rus: "читать" },
	{ eng: "hand", rus: "рука" },
	{ eng: "port", rus: "порт" },
	{ eng: "large", rus: "большой" },
	{ eng: "spell", rus: "читать по буквам" },
	{ eng: "add", rus: "добавлять" },
	{ eng: "even", rus: "даже" },
	{ eng: "land", rus: "земля" },
	{ eng: "here", rus: "здесь" },
	{ eng: "must", rus: "должен" },
	{ eng: "big", rus: "большой" },
	{ eng: "high", rus: "высокий" },
	{ eng: "such", rus: "такой" },
	{ eng: "follow", rus: "следовать" },
	{ eng: "act", rus: "действовать" },
	{ eng: "why", rus: "почему" },
	{ eng: "ask", rus: "спрашивать" },
	{ eng: "men  ", rus: "  люди" },
	{ eng: "change", rus: "менять" },
	{ eng: "went", rus: "отправился" },
	{ eng: "light", rus: "свет / легкий" },
	{ eng: "kind", rus: "добрый / разновидность" },
	{ eng: "off", rus: "от / выключенный" },
	{ eng: "need", rus: "необходимость" },
	{ eng: "house", rus: "дом" },
	{ eng: "picture", rus: "картина / фото" },
	{ eng: "try", rus: "пробовать / пытаться" },
	{ eng: "us", rus: "нас" },
	{ eng: "again", rus: "снова" },
	{ eng: "animal", rus: "животное" },
	{ eng: "point", rus: "точка" },
	{ eng: "mother", rus: "мать" },
	{ eng: "world", rus: "мир" },
	{ eng: "near", rus: "близко" },
	{ eng: "build", rus: "строить" },
	{ eng: "self", rus: "себя" },
	{ eng: "earth", rus: "земля" },
	{ eng: "father", rus: "отец" },
	{ eng: "any", rus: "любой" },
	{ eng: "new", rus: "новый" },
	{ eng: "work", rus: "работа" },
	{ eng: "part", rus: "часть" },
	{ eng: "take", rus: "брать" },
	{ eng: "get  ", rus: " получать" },
	{ eng: "place", rus: "место" },
	{ eng: "made", rus: "сделать" },
	{ eng: "live", rus: "жить" },
	{ eng: "where", rus: "где" },
	{ eng: "after", rus: "после" },
	{ eng: "back", rus: "назад" },
	{ eng: "little ", rus: " немного" },
	{ eng: "only", rus: "только" },
	{ eng: "round", rus: "круглый / вокруг" },
	{ eng: "man", rus: "мужчина" },
	{ eng: "year", rus: "год" },
	{ eng: "came", rus: "пришел" },
	{ eng: "show", rus: "показывать" },
	{ eng: "every", rus: "каждый" },
	{ eng: "good", rus: "хороший" },
	{ eng: "me", rus: "мне" },
	{ eng: "give", rus: "давать" },
	{ eng: "our", rus: "наш" },
	{ eng: "under", rus: "под" },
	{ eng: "name", rus: "имя" },
	{ eng: "very", rus: "очень" },
	{ eng: "through", rus: "через" },
	{ eng: "just", rus: "только / просто" },
	{ eng: "form", rus: "вид, форма / образовывать" },
	{ eng: "sentence", rus: "предложение" },
	{ eng: "great", rus: "отличный" },
	{ eng: "think", rus: "думать" },
	{ eng: "say", rus: "говорить" },
	{ eng: "help", rus: "помогать, помощь" },
	{ eng: "low", rus: " низкий" },
	{ eng: "line", rus: "линия, черта" },
	{ eng: "differ", rus: "отличаться" },
	{ eng: "turn", rus: "поворачивать" },
	{ eng: "cause", rus: "причина" },
	{ eng: "much", rus: "много" },
	{ eng: "mean ", rus: "значить / подлый / средний" },
	{ eng: "before", rus: "до" },
	{ eng: "move", rus: "двигать" },
	{ eng: "right", rus: "право / верный" },
	{ eng: "boy", rus: "мальчик" },
	{ eng: "old", rus: "старый" },
	{ eng: "too", rus: "тоже" },
	{ eng: "same", rus: "также" },
	{ eng: "she", rus: "она" },
	{ eng: "all", rus: "все" },
	{ eng: "there", rus: "там" },
	{ eng: "when", rus: "когда" },
	{ eng: "up", rus: "вверх / подниматься" },
	{ eng: "use", rus: "использовать" },
	{ eng: "your", rus: "твой" },
	{ eng: "way", rus: "путь" },
	{ eng: "about", rus: "о" },
	{ eng: "many", rus: "много" },
	{ eng: "then", rus: "затем" },
	{ eng: "them", rus: "их" },
	{ eng: "write", rus: "писать" },
	{ eng: "would", rus: "бы / было бы" },
	{ eng: "like", rus: "нравиться" },
	{ eng: "so", rus: "так" },
	{ eng: "these", rus: "эти" },
	{ eng: "her", rus: "ее" },
	{ eng: "long", rus: "долго / длинный" },
	{ eng: "make", rus: "делать" },
	{ eng: "thing", rus: "вещь" },
	{ eng: "see", rus: "видеть" },
	{ eng: "him", rus: "его" },
	{ eng: "two", rus: "два / двое" },
	{ eng: "has", rus: "имеет" },
	{ eng: "look", rus: "смотреть / взгляд" },
	{ eng: "more", rus: "больше" },
	{ eng: "day", rus: "день" },
	{ eng: "could", rus: "мог" },
	{ eng: "go", rus: "идти" },
	{ eng: "come", rus: "приходить" },
	{ eng: "did", rus: "сделал" },
	{ eng: "number", rus: "номер" },
	{ eng: "sound", rus: "звук" },
	{ eng: "no", rus: "нет" },
	{ eng: "most", rus: "самый / большинство" },
	{ eng: "people", rus: "люди" },
	{ eng: "my", rus: "мой" },
	{ eng: "over", rus: "над" },
	{ eng: "know", rus: "знать" },
	{ eng: "water", rus: "вода" },
	{ eng: "than", rus: "чем" },
	{ eng: "call", rus: "звонить / звонок" },
	{ eng: "first", rus: "первый" },
	{ eng: "who", rus: "кто" },
	{ eng: "may", rus: "может" },
	{ eng: "down", rus: "вниз" },
	{ eng: "side", rus: "сторона" },
	{ eng: "been", rus: "был" },
	{ eng: "now", rus: "сейчас" },
	{ eng: "find", rus: "найти" },
	{ eng: "head", rus: "голова" },
	{ eng: "stand", rus: "стоять" },
	{ eng: "own", rus: "свой / владеть" },
	{ eng: "page", rus: "страница" },
	{ eng: "should", rus: "должен" },
	{ eng: "country", rus: "страна" },
	{ eng: "found", rus: "найденный" },
	{ eng: "answer", rus: "ответ / отвечать" },
	{ eng: "school", rus: "школа" },
	{ eng: "grow", rus: "расти" },
	{ eng: "study", rus: "изучать" },
	{ eng: "still", rus: "все еще" },
	{ eng: "learn", rus: "учиться" },
	{ eng: "plant", rus: "растение / сажать" },
	{ eng: "cover", rus: "накрывать / обложка" },
	{ eng: "food", rus: "еда" },
	{ eng: "sun", rus: "солнце" },
	{ eng: "four", rus: "четыре" },
	{ eng: "between", rus: "между" },
	{ eng: "state", rus: "состояние, государство, штат " },
	{ eng: "keep", rus: "держать, продолжать" },
	{ eng: "eye", rus: "глаз" },
	{ eng: "never", rus: "никогда" },
	{ eng: "last", rus: "последний" },
	{ eng: "let", rus: "позволять" },
	{ eng: "thought", rus: "мысль / думал" },
	{ eng: "city", rus: "город" },
	{ eng: "tree", rus: "дерево" },
	{ eng: "cross", rus: "пересекать / крест" },
	{ eng: "farm", rus: "ферма" },
	{ eng: "hard", rus: "тяжелый / твердый" },
	{ eng: "start", rus: "начинать" },
	{ eng: "might", rus: "может быть / мощь" },
	{ eng: "story", rus: "история" },
	{ eng: "saw", rus: "—&nbsp;увидел / пила" },
	{ eng: "far", rus: "далеко" },
	{ eng: "sea", rus: "море" },
	{ eng: "draw", rus: "рисовать" },
	{ eng: "left", rus: "лево / оставил" },
	{ eng: "late", rus: "поздно" },
	{ eng: "run", rus: "бежать" },
	{ eng: "don’t", rus: "не" },
	{ eng: "while", rus: "в то время, как" },
	{ eng: "press", rus: "нажимать / давить" },
	{ eng: "close", rus: "близко / закрывать" },
	{ eng: "night", rus: "ночь" },
	{ eng: "real", rus: "реальный" },
	{ eng: "life", rus: "жизнь" },
	{ eng: "few", rus: "несколько" },
	{ eng: "north", rus: "север" },
	{ eng: "book", rus: "книга" },
	{ eng: "carry", rus: "нести &nbsp;" },
	{ eng: "took", rus: "взял" },
	{ eng: "science", rus: "наука" },
	{ eng: "eat", rus: "есть" },
	{ eng: "room", rus: "комната" },
	{ eng: "friend", rus: "друг" },
	{ eng: "began", rus: "началось" },
	{ eng: "idea", rus: "идея" },
	{ eng: "fish", rus: "рыба" },
	{ eng: "mountain", rus: "гора" },
	{ eng: "stop", rus: "остановка / останавливать " },
	{ eng: "once", rus: "однажды" },
	{ eng: "base", rus: "базовый / основывать" },
	{ eng: "hear", rus: "слышать" },
	{ eng: "horse", rus: "лошадь" },
	{ eng: "cut", rus: "резать" },
	{ eng: "sure", rus: "конечно / уверен" },
	{ eng: "watch", rus: "смотреть / часы" },
	{ eng: "colour", rus: "цвет" },
	{ eng: "face", rus: "лицо" },
	{ eng: "wood", rus: "дерево" },
	{ eng: "main", rus: "главный" },
	{ eng: "open", rus: "открыть" },
	{ eng: "seem", rus: "казаться" },
	{ eng: "together", rus: "вместе" },
	{ eng: "next", rus: "следующий" },
	{ eng: "white", rus: "белый" },
	{ eng: "children", rus: "дети" },
	{ eng: "begin", rus: "начинать" },
	{ eng: "got", rus: "получил" },
	{ eng: "walk", rus: "гулять / прогулка" },
	{ eng: "example", rus: "пример" },
	{ eng: "ease", rus: "легкость / облегчать" },
	{ eng: "paper", rus: "бумага" },
	{ eng: "group", rus: "группа" },
	{ eng: "always", rus: "всегда" },
	{ eng: "music", rus: "музыка" },
	{ eng: "those", rus: "те" },
	{ eng: "both", rus: "оба" },
	{ eng: "mark", rus: "отметка / отмечать" },
	{ eng: "often", rus: "часто" },
	{ eng: "letter", rus: "письмо" },
	{ eng: "until", rus: "до тех пор" },
	{ eng: "mile", rus: "миля" },
	{ eng: "river", rus: "река" },
	{ eng: "car", rus: "машина" },
	{ eng: "feet", rus: "ноги" },
	{ eng: "care", rus: "заботиться / уход" },
	{ eng: "second", rus: "секунда" },
	{ eng: "enough", rus: "достаточно / довольно" },
	{ eng: "plain", rus: "простой" },
	{ eng: "girl", rus: "девочка" },
	{ eng: "usual", rus: "обычно" },
	{ eng: "young", rus: "молодой" },
	{ eng: "ready", rus: "готовый" },
	{ eng: "above", rus: "выше" },
	{ eng: "ever", rus: "когда-либо" },
	{ eng: "red", rus: "красный" },
	{ eng: "list", rus: "список" },
	{ eng: "though", rus: "хоть" },
	{ eng: "feel", rus: "чувствовать" },
	{ eng: "talk", rus: "говорить" },
	{ eng: "bird", rus: "птица" },
	{ eng: "soon", rus: "скоро" },
	{ eng: "body", rus: "тело" },
	{ eng: "dog", rus: "собака" },
	{ eng: "family", rus: "семья" },
	{ eng: "direct", rus: "непосредственный / направлять" },
	{ eng: "pose", rus: "поза / позировать" },
	{ eng: "leave", rus: "покидать" },
	{ eng: "song", rus: "песня" },
	{ eng: "measure", rus: "мера / измерять" },
	{ eng: "door", rus: "дверь" },
	{ eng: "product", rus: "продукт" },
	{ eng: "black", rus: "черный" },
	{ eng: "short", rus: "короткий" },
	{ eng: "numeral", rus: "числительное" },
	{ eng: "class", rus: "класс / сорт" },
	{ eng: "wind", rus: "ветер" },
	{ eng: "question", rus: "вопрос" },
	{ eng: "happen", rus: "случаться" },
	{ eng: "complete", rus: "полный / завершенный " },
	{ eng: "ship ", rus: "корабль" },
	{ eng: "area", rus: "площадь / зона" },
	{ eng: "half", rus: "половина" },
	{ eng: "rock", rus: "рок / камень / скала" },
	{ eng: "order", rus: "заказ / порядок" },
	{ eng: "fire ", rus: "огонь" },
	{ eng: "south", rus: "юг" },
	{ eng: "problem", rus: "проблема" },
	{ eng: "piece", rus: "часть / кусок &nbsp;" },
	{ eng: "told", rus: "говорил" },
	{ eng: "knew", rus: "знал" },
	{ eng: "pass", rus: "проходить / передача" },
	{ eng: "since", rus: "с / поскольку" },
	{ eng: "top", rus: "верх / вершина" },
	{ eng: "whole", rus: "весь / целый" },
	{ eng: "king", rus: "король" },
	{ eng: "street", rus: "улица" },
	{ eng: "inch", rus: "дюйм" },
	{ eng: "multiply", rus: "умножать" },
	{ eng: "nothing", rus: "ничего" },
	{ eng: "course", rus: "курс / блюдо" },
	{ eng: "stay", rus: "оставаться" },
	{ eng: "wheel", rus: "колесо" },
	{ eng: "full", rus: "полный" },
	{ eng: "force", rus: "сила / заставлять" },
	{ eng: "blue", rus: "голубой / синий / грустный " },
	{ eng: "object", rus: "объект" },
	{ eng: "decide", rus: "решать" },
	{ eng: "surface", rus: "поверхность" },
	{ eng: "deep", rus: "глубоко" },
	{ eng: "moon", rus: "луна" },
	{ eng: "island", rus: "остров" },
	{ eng: "foot", rus: "нога" },
	{ eng: "system", rus: "система" },
	{ eng: "busy", rus: "занят" },
	{ eng: "test", rus: "тест / проверять" },
	{ eng: "record", rus: "записывать" },
	{ eng: "boat", rus: "лодка" },
	{ eng: "common", rus: "общий / обычный" },
	{ eng: "gold", rus: "золото" },
	{ eng: "possible", rus: "возможный" },
	{ eng: "plane", rus: "самолет / плоскость" },
	{ eng: "stead", rus: "место" },
	{ eng: "dry", rus: "сухой" },
	{ eng: "wonder", rus: "чудо / удивляться" },
	{ eng: "laugh", rus: "смех / смеяться" },
	{ eng: "thousand", rus: "тысяча" },
	{ eng: "ago", rus: "тому назад" },
	{ eng: "ran", rus: "побежал" },
	{ eng: "check", rus: "проверять" },
	{ eng: "game", rus: "игра" },
	{ eng: "shape", rus: "форма" },
	{ eng: "equate", rus: "приравнивать" },
	{ eng: "OK", rus: "хорошо" },
	{ eng: "miss", rus: "скучать / пропускать" },
	{ eng: "brought", rus: "привел" },
	{ eng: "heat", rus: "жара, высокая температура " },
	{ eng: "snow", rus: "снег" },
	{ eng: "tire", rus: "шина / утомлять" },
	{ eng: "bring", rus: "приносить" },
	{ eng: "yes", rus: "да" },
	{ eng: "distant", rus: "отдаленный" },
	{ eng: "fill", rus: "наполнять" },
	{ eng: "east", rus: "восток" },
	{ eng: "paint", rus: "краска / красить" },
	{ eng: "language", rus: "язык" },
	{ eng: "among", rus: "среди" },
	{ eng: "unit", rus: "единица" },
	{ eng: "power", rus: "мощность / сила" },
	{ eng: "town", rus: "город" },
	{ eng: "fine", rus: "отлично" },
	{ eng: "certain", rus: "определенный" },
	{ eng: "fly", rus: "летать" },
	{ eng: "fall", rus: "падать / осень" },
	{ eng: "lead", rus: "вести / руководить" },
	{ eng: "cry", rus: "плакать" },
	{ eng: "dark", rus: "темный, темнота" },
	{ eng: "machine", rus: "машина / механизм" },
	{ eng: "note", rus: "примечание / отмечать" },
	{ eng: "wait", rus: "ждать" },
	{ eng: "plan", rus: "план" },
	{ eng: "figure", rus: "цифра / фигура" },
	{ eng: "star", rus: "звезда" },
	{ eng: "box", rus: "коробка" },
	{ eng: "noun", rus: "существительное" },
	{ eng: "field", rus: "поле" },
	{ eng: "rest", rus: "остальное / отдыхать" },
	{ eng: "correct", rus: "поправлять / правильный " },
	{ eng: "able", rus: "в состоянии / способный" },
	{ eng: "pound", rus: "фунт" },
	{ eng: "done", rus: "сделанный" },
	{ eng: "beauty", rus: "красота" },
	{ eng: "drive", rus: "водить" },
	{ eng: "stood", rus: "стоял" },
	{ eng: "contain", rus: "содержать" },
	{ eng: "front", rus: "перед" },
	{ eng: "teach", rus: "обучать" },
	{ eng: "week", rus: "неделя" },
	{ eng: "final", rus: "финал / последний" },
	{ eng: "gave", rus: "дал" },
	{ eng: "green", rus: "зеленый" },
	{ eng: "oh", rus: "ох" },
	{ eng: "quick", rus: "быстро" },
	{ eng: "develop", rus: "развивать" },
	{ eng: "ocean ", rus: "океан" },
	{ eng: "warm", rus: "тепло" },
	{ eng: "free", rus: "свободный" },
	{ eng: "minute", rus: "минута" },
	{ eng: "strong", rus: "сильный" },
	{ eng: "special ", rus: " особый" },
	{ eng: "mind", rus: "разум / возражать" },
	{ eng: "behind", rus: "позади" },
	{ eng: "clear", rus: "ясный / понятно" },
	{ eng: "tail", rus: "хвост" },
	{ eng: "produce", rus: "производить" },
	{ eng: "fact", rus: "факт &nbsp;" },
	{ eng: "space", rus: "пространство / космос" },
	{ eng: "heard", rus: "слышал" },
	{ eng: "best", rus: "лучший" },
	{ eng: "hour", rus: "час" },
	{ eng: "better", rus: "лучше" },
	{ eng: "true", rus: "правда &nbsp;" },
	{ eng: "during", rus: "—&nbsp;в течение" },
	{ eng: "hundred", rus: "сотня" },
	{ eng: "five", rus: "пять" },
	{ eng: "remember", rus: "помнить" },
	{ eng: "step", rus: "шаг" },
	{ eng: "early", rus: "ранний / рано" },
	{ eng: "hold", rus: "держать" },
	{ eng: "west", rus: "запад" },
	{ eng: "ground", rus: "земля" },
	{ eng: "interest", rus: "интерес" },
	{ eng: "reach", rus: "достигать" },
	{ eng: "fast", rus: "быстро" },
	{ eng: "verb", rus: "глагол" },
	{ eng: "sing", rus: "петь" },
	{ eng: "listen", rus: "слушать" },
	{ eng: "six", rus: "шесть" },
	{ eng: "table", rus: "стол" },
	{ eng: "travel", rus: "путешествовать" },
	{ eng: "less", rus: "меньше" },
	{ eng: "morning", rus: "утро" },
	{ eng: "ten", rus: "десять" },
	{ eng: "simple", rus: "просто / простой" },
	{ eng: "several", rus: "несколько" },
	{ eng: "vowel", rus: "гласный (звук)" },
	{ eng: "towards", rus: "к / по направлению к " },
	{ eng: "war", rus: "война" },
	{ eng: "lay", rus: "лежать" },
	{ eng: "against", rus: "против" },
	{ eng: "pattern", rus: "узор" },
	{ eng: "slow", rus: "медленно / медленный" },
	{ eng: "center", rus: "центр" },
	{ eng: "love", rus: "любовь" },
	{ eng: "person", rus: "человек" },
	{ eng: "money", rus: "деньги" },
	{ eng: "serve", rus: "обслуживать &nbsp;" },
	{ eng: "appear", rus: "появляться" },
	{ eng: "road", rus: "дорога" },
	{ eng: "map", rus: "карта" },
	{ eng: "rain", rus: "дождь" },
	{ eng: "rule", rus: "правило" },
	{ eng: "govern", rus: "управлять" },
	{ eng: "pull", rus: "тянуть" },
	{ eng: "cold", rus: "холодный" },
	{ eng: "notice", rus: "уведомление / замечать " },
	{ eng: "voice", rus: "голос" },
	{ eng: "energy", rus: "энергия" },
	{ eng: "hunt", rus: "охотититься" },
	{ eng: "probable", rus: "вероятный" },
	{ eng: "bed", rus: "кровать" },
	{ eng: "brother", rus: "&nbsp;брат" },
	{ eng: "egg", rus: "яйцо" },
	{ eng: "ride", rus: "ездить / поездка" },
	{ eng: "cell", rus: "клетка / мобильный )" },
	{ eng: "believe", rus: "верить" },
	{ eng: "perhaps", rus: "возможно" },
	{ eng: "pick", rus: "выбирать" },
	{ eng: "sudden", rus: " &nbsp;внезапный" },
	{ eng: "count", rus: "считать" },
	{ eng: "square", rus: "квадрат / площадь" },
	{ eng: "reason", rus: "причина" },
	{ eng: "length", rus: "длина" },
	{ eng: "represent", rus: "представлять" },
	{ eng: "art", rus: "искусство" },
	{ eng: "subject", rus: "предмет" },
	{ eng: "region", rus: "регион" },
	{ eng: "size", rus: "размер" },
	{ eng: "vary", rus: "меняться / варьировать " },
	{ eng: "settle", rus: "селиться" },
	{ eng: "speak", rus: "говорить" },
	{ eng: "weight", rus: "вес" },
	{ eng: "general", rus: "главный / общий" },
	{ eng: "ice", rus: "лед" },
	{ eng: "matter", rus: "иметь значение / предмет /	материя" },
	{ eng: "circle", rus: "круг" },
	{ eng: "pair", rus: "пара" },
	{ eng: "include", rus: "включать в себя" },
	{ eng: "divide", rus: "разделять" },
	{ eng: "syllable", rus: "слог" },
	{ eng: "felt", rus: "чувствовал" },
	{ eng: "grand", rus: "большой / великий" },
	{ eng: "ball", rus: "мяч" },
	{ eng: "yet", rus: "еще" },
	{ eng: "wave", rus: "волна" },
	{ eng: "drop", rus: "капля / бросать" },
	{ eng: "heart", rus: "сердце" },
	{ eng: "AM", rus: "до полудня" },
	{ eng: "present", rus: "подарок / настоящий" },
	{ eng: "heavy", rus: "тяжелый" },
	{ eng: "dance", rus: "танец / танцевать" },
	{ eng: "engine", rus: "двигатель" },
	{ eng: "position", rus: "позиция" },
	{ eng: "arm", rus: "рука" },
	{ eng: "wide", rus: "широкий / повсюду" },
	{ eng: "sail", rus: "паруса / плавать" },
	{ eng: "material", rus: "материал" },
	{ eng: "fraction", rus: "доля" },
	{ eng: "forest", rus: "лес" },
	{ eng: "sit", rus: "сидеть" },
	{ eng: "race", rus: "гонка / раса" },
	{ eng: "window", rus: "окно" },
	{ eng: "store ", rus: "магазин" },
	{ eng: "summer", rus: "лето" },
	{ eng: "train", rus: "поезд" },
	{ eng: "sleep", rus: "спать" },
	{ eng: "prove", rus: "доказывать" },
	{ eng: "alone", rus: "один / одинокий" },
	{ eng: "leg", rus: "нога" },
	{ eng: "exercise", rus: "упражнение" },
	{ eng: "wall", rus: "стена" },
	{ eng: "catch", rus: "поймать" },
	{ eng: "mount", rus: "взбираться / монтировать " },
	{ eng: "wish", rus: "желать" },
	{ eng: "sky", rus: "небо" },
	{ eng: "board", rus: "доска" },
	{ eng: "joy", rus: "радость" },
	{ eng: "winter", rus: "зима" },
	{ eng: "somebody", rus: "кто-то" },
	{ eng: "written", rus: "написанный" },
	{ eng: "wild", rus: "дикий" },
	{ eng: "instrument", rus: "инструмент" },
	{ eng: "kept", rus: "сохранил" },
	{ eng: "glass", rus: "стекло" },
	{ eng: "grass", rus: "трава" },
	{ eng: "cow", rus: "корова" },
	{ eng: "job", rus: "работа" },
	{ eng: "edge", rus: "край" },
	{ eng: "sign", rus: "подписывать / знак" },
	{ eng: "visit", rus: "посещать" },
	{ eng: "past", rus: "прошлое" },
	{ eng: "soft", rus: "мягкий" },
	{ eng: "fun", rus: "веселый / веселье" },
	{ eng: "bright", rus: "яркий" },
	{ eng: "gas", rus: "газ / бензин " },
	{ eng: "weather", rus: "погода" },
	{ eng: "month", rus: "месяц" },
	{ eng: "million", rus: "миллион" },
	{ eng: "bear", rus: "медведь / выносить (терпеть)" },
	{ eng: "finish", rus: "закончить" },
	{ eng: "happy", rus: "счастливый" },
	{ eng: "hope", rus: "надежда / надеяться" },
	{ eng: "flower", rus: "цветок" },
	{ eng: "clothes", rus: "одежда" },
	{ eng: "strange", rus: "странный" },
	{ eng: "gone", rus: "ушедший" },
	{ eng: "trade", rus: "торговля" },
	{ eng: "melody", rus: "мелодия" },
	{ eng: "trip", rus: "поездка" },
	{ eng: "office", rus: "офис" },
	{ eng: "receive", rus: "получать" },
	{ eng: "row", rus: "ряд" },
	{ eng: "mouth", rus: "рот" },
	{ eng: "exact", rus: "точный" },
	{ eng: "symbol", rus: "символ" },
	{ eng: "die", rus: "умирать" },
	{ eng: "least", rus: "наименее / меньше всего " },
	{ eng: "trouble", rus: "проблема" },
	{ eng: "shout", rus: "кричать" },
	{ eng: "except", rus: "кроме / исключая" },
	{ eng: "writer", rus: "писатель" },
	{ eng: "seed", rus: "семя" },
	{ eng: "tone", rus: "тон &nbsp;" },
	{ eng: "join", rus: "присоединяться" },
	{ eng: "suggest", rus: "предлагать" },
	{ eng: "clean", rus: "чисто / чистый" },
	{ eng: "break", rus: "перерыв / ломать" },
	{ eng: "lady", rus: "леди" },
	{ eng: "yard", rus: "двор" },
	{ eng: "rise", rus: "рост / подниматься" },
	{ eng: "bad", rus: "плохой" },
	{ eng: "blow", rus: "удар / дуть" },
	{ eng: "oil", rus: "масло" },
	{ eng: "blood", rus: "кровь" },
	{ eng: "touch", rus: "трогать / прикосновение" },
	{ eng: "goal", rus: "цель" },
	{ eng: "cent", rus: "цент" },
	{ eng: "mix", rus: "смесь / смешивать" },
	{ eng: "team", rus: "команда" },
	{ eng: "wire", rus: "проволока" },
	{ eng: "cost", rus: "стоимость" },
	{ eng: "lost", rus: "потерял / потерянный" },
	{ eng: "brown", rus: "коричневый" },
	{ eng: "wear", rus: "носить" },
	{ eng: "garden", rus: "сад" },
	{ eng: "equal", rus: "равный" },
	{ eng: "sent", rus: "отправил / отправленный " },
	{ eng: "choose", rus: "выбирать" },
	{ eng: "feel", rus: "чувствовать" },
	{ eng: "fit", rus: "соответствовать / подходить " },
	{ eng: "flow", rus: "поток / течь" },
	{ eng: "fair", rus: "ярмарка / честный" },
	{ eng: "bank", rus: "банк" },
	{ eng: "collect", rus: "собирать" },
	{ eng: "save", rus: "сохранять" },
	{ eng: "control", rus: "контроль / контролировать" },
	{ eng: "decimal", rus: "десятичный" },
	{ eng: "ear", rus: "ухо" },
	{ eng: "else", rus: "еще" },
	{ eng: "quite", rus: "довольно" },
	{ eng: "broke", rus: "сломал / без денег" },
	{ eng: "case", rus: "случай" },
	{ eng: "middle", rus: "средний" },
	{ eng: "kill", rus: "убивать" },
	{ eng: "son", rus: "сын" },
	{ eng: "lake", rus: "озеро" },
	{ eng: "moment", rus: "момент" },
	{ eng: "scale", rus: "шкала" },
	{ eng: "loud", rus: "громко" },
	{ eng: "spring", rus: "весна" },
	{ eng: "observe", rus: "наблюдать" },
	{ eng: "child", rus: "ребенок" },
	{ eng: "straight", rus: "прямо / прямой" },
	{ eng: "consonant", rus: "согласный (звук)" },
	{ eng: "nation", rus: "нация" },
	{ eng: "dictionary", rus: "словарь" },
	{ eng: "milk", rus: "молоко" },
	{ eng: "speed", rus: "скорость" },
	{ eng: "method", rus: "метод" },
	{ eng: "organ", rus: "орган" },
	{ eng: "pay", rus: "платить" },
	{ eng: "age", rus: "возраст" },
	{ eng: "section", rus: "раздел" },
	{ eng: "dress", rus: "платье / одеваться" },
	{ eng: "cloud", rus: "облако" },
	{ eng: "surprise", rus: "сюрприз" },
	{ eng: "quiet", rus: "тихо / тихий" },
	{ eng: "stone", rus: "камень" },
	{ eng: "tiny", rus: "крошечный" },
	{ eng: "climb", rus: "подъем / взбираться" },
	{ eng: "cool", rus: "крутой / прохладно" },
	{ eng: "design", rus: "дизайн" },
	{ eng: "poor", rus: "бедный" },
	{ eng: "lot", rus: "много" },
	{ eng: "explain", rus: "объяснять" },
	{ eng: "bottom", rus: "низ" },
	{ eng: "key", rus: "ключ" },
	{ eng: "iron", rus: "железо" },
	{ eng: "single", rus: "один" },
	{ eng: "stick", rus: "придерживаться / приклеивать" },
	{ eng: "flat", rus: "квартира  / плоский" },
	{ eng: "twenty", rus: "двадцать" },
	{ eng: "skin", rus: "кожа" },
	{ eng: "smile", rus: "улыбка" },
	{ eng: "crease", rus: "складка / мять" },
	{ eng: "hole", rus: "дыра" },
	{ eng: "jump", rus: "прыгать" },
	{ eng: "baby", rus: "ребенок" },
	{ eng: "eight", rus: "восемь" },
	{ eng: "village", rus: "деревня" },
	{ eng: "meet", rus: "встречать" },
	{ eng: "root", rus: "корень" },
	{ eng: "buy", rus: "покупать" },
	{ eng: "raise", rus: "поднимать / повышать" },
	{ eng: "solve", rus: "решать" },
	{ eng: "metal", rus: "металл" },
	{ eng: "whether", rus: "будь то / ли" },
	{ eng: "push", rus: "давить / нажимать" },
	{ eng: "seven", rus: "семь" },
	{ eng: "paragraph", rus: "параграф" },
	{ eng: "third", rus: "третий" },
	{ eng: "shall", rus: "должен" },
	{ eng: "held", rus: "держал" },
	{ eng: "hair", rus: "волосы" },
	{ eng: "describe", rus: "описывать" },
	{ eng: "cook", rus: "готовить" },
	{ eng: "floor", rus: "пол" },
	{ eng: "either", rus: "или" },
	{ eng: "result", rus: "результат" },
	{ eng: "burn", rus: "гореть / ожог" },
	{ eng: "hill", rus: "холм" },
	{ eng: "safe", rus: "безопасный" },
	{ eng: "cat", rus: "кот / кошка" },
	{ eng: "century", rus: "век / столетие" },
	{ eng: "consider", rus: "рассматривать" },
	{ eng: "type", rus: "тип / печатать" },
	{ eng: "law", rus: "закон" },
	{ eng: "bit", rus: "немного / часть" },
	{ eng: "coast", rus: "берег" },
	{ eng: "copy", rus: "копировать / копия" },
	{ eng: "phrase", rus: "фраза / формулировать" },
	{ eng: "silent", rus: "тихий" },
	{ eng: "tall", rus: "высокий" },
	{ eng: "sand", rus: "песок" },
	{ eng: "soil", rus: "почва" },
	{ eng: "roll", rus: "вертеть" },
	{ eng: "temperature", rus: "температура" },
	{ eng: "finger", rus: "палец" },
	{ eng: "industry", rus: "индустрия" },
	{ eng: "value", rus: "значение / стоимость /ценность" },
	{ eng: "fight", rus: "драка / бороться" },
	{ eng: "lie", rus: "ложь / лгать" },
	{ eng: "beat", rus: "бить / ритм" },
	{ eng: "excite", rus: "возбуждать" },
	{ eng: "natural", rus: "натуральный" },
	{ eng: "view", rus: "вид" },
	{ eng: "sense", rus: "смысл / чувство" },
	{ eng: "capital", rus: "столица" },
	{ eng: "won’t", rus: "не будет" },
	{ eng: "chair", rus: "стул" },
	{ eng: "danger", rus: "опасность" },
	{ eng: "fruit", rus: "фрукт" },
	{ eng: "rich", rus: "богатый" },
	{ eng: "thick", rus: "толстый" },
	{ eng: "soldier", rus: "солдат" },
	{ eng: "process", rus: "процесс / подвергать обработке" },
	{ eng: "operate", rus: "управлять" },
	{ eng: "practice", rus: "практиковать / практика" },
	{ eng: "separate", rus: "разделять" },
	{ eng: "difficult", rus: "сложный" },
	{ eng: "doctor", rus: "доктор" },
	{ eng: "please", rus: "пожалуйста / угождать" },
	{ eng: "protect", rus: "защищать" },
	{ eng: "noon", rus: "полдень" },
	{ eng: "crop", rus: "обрезать / урожай" },
	{ eng: "modern", rus: "современный" },
	{ eng: "element", rus: "элемент" },
	{ eng: "hit", rus: "удар / бить" },
	{ eng: "student", rus: "студент" },
	{ eng: "corner", rus: "угол" },
	{ eng: "party", rus: "вечеринка / партия" },
	{ eng: "supply", rus: "поставка / снабжать" },
	{ eng: "whose", rus: "чьи" },
	{ eng: "locate", rus: "размещать" },
	{ eng: "ring", rus: "кольцо" },
	{ eng: "character", rus: "персонаж / характер " },
	{ eng: "insect", rus: "насекомое" },
	{ eng: "caught", rus: "поймал / пойманный" },
	{ eng: "period", rus: "период / точка" },
	{ eng: "indicate", rus: "указывать" },
	{ eng: "radio", rus: "радио" },
	{ eng: "spoke", rus: "говорил" },
	{ eng: "atom", rus: "атом" },
	{ eng: "human", rus: "человек" },
	{ eng: "history", rus: "история" },
	{ eng: "effect", rus: "эффект / следствие" },
	{ eng: "electric", rus: "электрический" },
	{ eng: "expect", rus: "ожидать &nbsp;" },
	{ eng: "bone", rus: "кость" },
	{ eng: "rail", rus: "рельс / железнодорожный путь	" },
	{ eng: "imagine", rus: "представлять" },
	{ eng: "provide", rus: "предоставлять" },
	{ eng: "agree", rus: "соглашаться" },
	{ eng: "thus", rus: "таким образом" },
	{ eng: "gentle", rus: "нежный" },
	{ eng: "woman", rus: "женщина" },
	{ eng: "captain", rus: "капитан" },
	{ eng: "guess", rus: "предположение / угадывать " },
	{ eng: "necessary", rus: "необходимый" },
	{ eng: "sharp", rus: "острый / умный / стильный (о человеке) " },
	{ eng: "wing", rus: "крыло" },
	{ eng: "create", rus: "создавать" },
	{ eng: "neighbour", rus: "сосед" },
	{ eng: "wash", rus: "мыть" },
	{ eng: "bat", rus: "летучая мышь / бита" },
	{ eng: "rather", rus: "скорее" },
	{ eng: "crowd", rus: "толпа" },
	{ eng: "corn", rus: "кукуруза" },
	{ eng: "compare", rus: "сравнивать" },
	{ eng: "poem", rus: "стих" },
	{ eng: "string", rus: "струна" },
	{ eng: "bell", rus: "колокол" },
	{ eng: "depend", rus: "зависеть" },
	{ eng: "meat", rus: "мясо" },
	{ eng: "rub", rus: "тереть" },
	{ eng: "tube", rus: "трубка / метро (в Лондоне)" },
	{ eng: "famous", rus: "известный" },
	{ eng: "dollar", rus: "доллар" },
	{ eng: "stream", rus: "поток / течь" },
	{ eng: "fear", rus: "страх / бояться" },
	{ eng: "sight", rus: "взгляд / вид / зрение" },
	{ eng: "thin", rus: "тонкий" },
	{ eng: "triangle", rus: "треугольник" },
	{ eng: "planet", rus: "планета" },
	{ eng: "hurry", rus: "торопиться / спешка" },
	{ eng: "chief", rus: "шеф" },
	{ eng: "colony", rus: "колония" },
	{ eng: "clock", rus: "часы" },
	{ eng: "mine", rus: "мой" },
	{ eng: "tie", rus: "галстук / завязывать" },
	{ eng: "enter", rus: "вход / входить" },
	{ eng: "major", rus: "майор / основной" },
	{ eng: "fresh", rus: "свежий" },
	{ eng: "search", rus: "поиск / искать" },
	{ eng: "send", rus: "посылать" },
	{ eng: "yellow", rus: "желтый" },
	{ eng: "gun", rus: "пистолет / ружье" },
	{ eng: "allow", rus: "позволять" },
	{ eng: "print", rus: "печать / печатать" },
	{ eng: "dead", rus: "мертвый" },
	{ eng: "spot", rus: "место / пятно" },
	{ eng: "desert", rus: "пустыня" },
	{ eng: "suit", rus: "костюм / подходить" },
	{ eng: "current", rus: "текущий" },
	{ eng: "lift", rus: "поднимать / лифт " },
	{ eng: "rose", rus: "роза" },
	{ eng: "arrive", rus: "прибывать" },
	{ eng: "master", rus: "мастер / главный /	справляться" },
	{ eng: "track", rus: "трек / след" },
	{ eng: "parent", rus: "родитель" },
	{ eng: "shore", rus: "побережье" },
	{ eng: "division", rus: "деление" },
	{ eng: "sheet", rus: "лист / простынь" },
	{ eng: "substance", rus: "вещество" },
	{ eng: "favour", rus: "одолжение" },
	{ eng: "connect", rus: "соединять" },
	{ eng: "post", rus: "почта / после" },
	{ eng: "spend", rus: "тратить" },
	{ eng: "chord", rus: "аккорд" },
	{ eng: "fat", rus: "жир / жирный" },
	{ eng: "glad", rus: "рад" },
	{ eng: "original", rus: "оригинальный" },
	{ eng: "share", rus: " делиться" },
	{ eng: "station", rus: "станция" },
	{ eng: "dad", rus: "папа" },
	{ eng: "bread", rus: "хлеб" },
	{ eng: "charge", rus: "заряд / заряжать" },
	{ eng: "proper", rus: "правильный" },
	{ eng: "bar", rus: "бар" },
	{ eng: "offer", rus: "предлагать / предложение " },
	{ eng: "segment", rus: "часть / сегмент" },
	{ eng: "slave", rus: "раб" },
	{ eng: "duck", rus: "утка" },
	{ eng: "instant", rus: "мгновенный" },
	{ eng: "market", rus: "рынок" },
	{ eng: "degree", rus: "температура" },
	{ eng: "populate", rus: "населять" },
	{ eng: "education", rus: "образование" },
	{ eng: "dear", rus: "дорогая" },
	{ eng: "enemy", rus: "враг" },
	{ eng: "reply", rus: "ответ / отвечать" },
	{ eng: "drink", rus: "напиток / пить" },
	{ eng: "occur", rus: "происходить" },
	{ eng: "support", rus: "поддержка / поддерживать" },
	{ eng: "speech", rus: "речь" },
	{ eng: "nature", rus: "природа" },
	{ eng: "range", rus: "диапазон" },
	{ eng: "steam", rus: "пар" },
	{ eng: "motion", rus: "движение" },
	{ eng: "path", rus: "путь" },
	{ eng: "liquid", rus: "жидкость" },
	{ eng: "violence", rus: "жестокость &nbsp;" },
	{ eng: "meant", rus: "значил" },
	{ eng: "quotient", rus: "частное" },
	{ eng: "teeth", rus: "зубы" },
	{ eng: "shell", rus: "ракушка" },
	{ eng: "neck", rus: "шея" },
	{ eng: "oxygen", rus: "кислород" },
	{ eng: "sugar", rus: "сахар" },
	{ eng: "death", rus: "смерть" },
	{ eng: "pretty", rus: "красивый / довольно" },
	{ eng: "skill", rus: "умение" },
	{ eng: "women", rus: "женщины" },
	{ eng: "season", rus: "сезон / время года" },
	{ eng: "solution", rus: "решение" },
	{ eng: "magnet", rus: "магнит" },
	{ eng: "silver", rus: "серебро" },
	{ eng: "thanks", rus: "спасибо &nbsp;" },
	{ eng: "lunch", rus: "ужин" },
	{ eng: "match", rus: "совпадать / матч" },
	{ eng: "treat", rus: "угощение / обращаться" },
	{ eng: "especially", rus: "особенно" },
	{ eng: "fail", rus: "провал / терпеть провал" },
	{ eng: "afraid", rus: "испуганный" },
	{ eng: "huge", rus: "огромный" },
	{ eng: "sister", rus: "сестра" },
	{ eng: "steel", rus: "сталь" },
	{ eng: "discuss", rus: "обсуждать" },
	{ eng: "forward", rus: "вперед" },
	{ eng: "similar", rus: "похожий" },
	{ eng: "guide", rus: "руководство / направлять " },
	{ eng: "experience", rus: "опыт" },
	{ eng: "score", rus: "очки / счет" },
	{ eng: "apple", rus: "яблоко" },
	{ eng: "evidence", rus: "доказательства" },
	{ eng: "message", rus: "сообщение" },
	{ eng: "movie", rus: "фильм " },
	{ eng: "coat", rus: "пальто" },
	{ eng: "mass", rus: "масса" },
	{ eng: "card", rus: "карта" },
	{ eng: "band", rus: "группа" },
	{ eng: "rope", rus: "веревка" },
	{ eng: "slip", rus: "скользить" },
	{ eng: "win", rus: "побеждать" },
	{ eng: "dream", rus: "мечта / мечтать / сон" },
	{ eng: "evening", rus: "вечер" },
	{ eng: "condition", rus: "состояние" },
	{ eng: "feed", rus: "кормить" },
	{ eng: "tool", rus: "инструмент" },
	{ eng: "total", rus: "сумма" },
	{ eng: "basic", rus: "базовый" },
	{ eng: "smell", rus: "запах" },
	{ eng: "valley", rus: "долина" },
	{ eng: "not", rus: "не" },
	{ eng: "double ", rus: " двойной / вдвойне / двойник" },
	{ eng: "seat", rus: "место" },
	{ eng: "continue", rus: "продолжать" },
	{ eng: "news", rus: "новости" },
	{ eng: "police", rus: "полиция" },
	{ eng: "hat", rus: "шляпа" },
	{ eng: "sell", rus: "продавать" },
	{ eng: "success", rus: "успех" },
	{ eng: "company", rus: "компания" },
	{ eng: "security", rus: "безопасность / охрана" },
	{ eng: "event", rus: "событие" },
	{ eng: "particular", rus: "особенный / конкретный" },
	{ eng: "deal", rus: "сделка / часть / разбираться" },
	{ eng: "swim", rus: "плавать" },
	{ eng: "term", rus: "срок / семестр / термин" },
	{ eng: "opposite", rus: "напротив /противоположный" },
	{ eng: "wife", rus: "жена" },
	{ eng: "shoes", rus: "обувь / туфли" },
	{ eng: "shoulders",  rus: "плечи" },
	{ eng: "spread", rus: "распространение /распространять" },
	{ eng: "arrange", rus: "организовывать" },
	{ eng: "camp", rus: "лагерь" },
	{ eng: "invent", rus: "изобретать" },
	{ eng: "cotton", rus: "хлопок" },
	{ eng: "born", rus: "родиться" },
	{ eng: "determine", rus: "определять" },
	{ eng: "quarter", rus: "четверть" },
	{ eng: "nine", rus: "девять" },
	{ eng: "remove", rus: "удалять" },
	{ eng: "noise", rus: "шум" },
	{ eng: "level", rus: "уровень" },
	{ eng: "chance", rus: "шанс" },
	{ eng: "gather", rus: "r собирать" },
	{ eng: "shop", rus: "магазин " },
	{ eng: "stretch", rus: "растягивать" },
	{ eng: "throw", rus: "бросать" },
	{ eng: "shine", rus: "сиять" },
	{ eng: "property", rus: "собственность" },
	{ eng: "issue", rus: "проблема" },
	{ eng: "legal", rus: "законный" },
	{ eng: "select", rus: "выбирать" },
	{ eng: "wrong", rus: "неправильный" },
	{ eng: "gray", rus: "серый" },
	{ eng: "repeat", rus: "повторять" },
	{ eng: "require", rus: "требоваться" },
	{ eng: "broad", rus: "широкий" },
	{ eng: "prepare", rus: "подготавливать" },
	{ eng: "salt", rus: "соль / соленый" },
	{ eng: "nose", rus: "нос" },
	{ eng: "plural", rus: "множественное число" },
	{ eng: "anger", rus: "гнев" },
	{ eng: "claim", rus: "запрос / требовать" },
	{ eng: "price ", rus: " цена" }
]

